export const destinations = [
  {
    id: "tanjung-bira",
    name: "Tanjung Bira",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -5.6126, lng: 120.4460 },
    description: "Temukan rute terbaik, pantai tersembunyi, dan highlights budaya lokal dalam satu tampilan peta yang bersih.",
    tags: ["Pantai", "Budaya", "Kuliner", "Adventure"],
    detailUrl: "/paket-wisata/tanjung-bira",
  },
  {
    id: "toraja",
    name: "Tana Toraja",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -2.9697, lng: 119.8983 },
    description: "Jelajahi warisan budaya Toraja dengan rumah adat Tongkonan dan ritual Rambu Solo yang megah.",
    tags: ["Budaya", "Sejarah", "Alam", "Kuliner"],
    detailUrl: "/paket-wisata/toraja",
  },
  {
    id: "malino",
    name: "Malino",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -5.2519, lng: 119.8502 },
    description: "Nikmati udara sejuk pegunungan Malino dengan kebun teh dan air terjun yang menakjubkan.",
    tags: ["Alam", "Rileks", "Kebun Teh"],
    detailUrl: "/paket-wisata/malino",
  },
  {
    id: "bantimurung",
    name: "Bantimurung",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -4.9000, lng: 119.7500 },
    description: "Taman nasional dengan ribuan kupu-kupu dan air terjun yang memukau.",
    tags: ["Alam", "Keluarga", "Petualangan"],
    detailUrl: "/paket-wisata/bantimurung",
  },
  {
    id: "selayar",
    name: "Selayar",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -6.1200, lng: 120.4620 },
    description: "Surga bawah laut dengan terumbu karang yang indah dan pantai pasir putih.",
    tags: ["Pantai", "Diving", "Snorkeling"],
    detailUrl: "/paket-wisata/selayar",
  },
  {
    id: "gowa",
    name: "Gowa",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -5.2098, lng: 119.4829 },
    description: "Kota bersejarah dengan benteng Somba Opu dan makam raja-raja Gowa.",
    tags: ["Sejarah", "Budaya", "Kuliner"],
    detailUrl: "/paket-wisata/gowa",
  },
  {
    id: "pangkep",
    name: "Pangkajene",
    origin: { name: "Makassar, Sulawesi Selatan", lat: -5.1477, lng: 119.4327 },
    coordinates: { lat: -4.9261, lng: 119.6048 },
    description: "Destinasi dengan keindahan pantai dan budaya lokal yang masih kental.",
    tags: ["Pantai", "Budaya", "Kuliner"],
    detailUrl: "/paket-wisata/pangkep",
  }
];
